### ISSUE TITLE
Is there any plan to support `@phpstan-*`

### ISSUE THREAD

**Issue by ecoms-ye** [ErnstStavroBlofeld/php-types#1]
Hello, thanks so much for providing this great tool!

Is there any plan to support `@phpstan-*` annotations?

**Reference**

- https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases
- https://phpstan.org/writing-php-code/narrowing-types#custom-type-checking-functions-and-methods

**Comment by zutritt** [comment]
Hi, glad you like it, i think i might be able to work on supporting those features over the weekend
